"""m2 schema — users, projects, analysis_jobs, analyses + node/community/comment tables

Revision ID: 0002_m2_schema
Revises: 0001_baseline
Create Date: 2026-09-08
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_m2_schema"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_projects_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("rq_job_id", sa.String(length=64), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_analysis_jobs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
    )
    op.create_index(
        op.f("ix_analysis_jobs_project_id"), "analysis_jobs", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_analysis_jobs_status"), "analysis_jobs", ["status"], unique=False)
    op.create_table(
        "analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("insufficient_data", sa.Boolean(), nullable=False),
        sa.Column("weak_structure", sa.Boolean(), nullable=False),
        sa.Column("approximated", sa.Boolean(), nullable=False),
        sa.Column("modularity", sa.Float(), nullable=True),
        sa.Column("resolution_used", sa.Float(), nullable=True),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("edge_count", sa.Integer(), nullable=False),
        sa.Column("community_count", sa.Integer(), nullable=False),
        sa.Column("fetched_comment_count", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sentiment_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_analyses_job_id_analysis_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_analyses_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
        sa.UniqueConstraint("job_id", name=op.f("uq_analyses_job_id")),
    )
    op.create_index(op.f("ix_analyses_project_id"), "analyses", ["project_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("external_ref", sa.String(length=64), nullable=False),
        sa.Column("author_pseudonym", sa.String(length=64), nullable=False),
        sa.Column("parent_author_pseudonym", sa.String(length=64), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("text_length", sa.Integer(), nullable=False),
        sa.Column("sentiment_label", sa.String(length=16), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("toxicity", sa.Float(), nullable=True),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.Column("failed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_comments_analysis_id_analyses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(op.f("ix_comments_analysis_id"), "comments", ["analysis_id"], unique=False)
    op.create_index(
        op.f("ix_comments_author_pseudonym"), "comments", ["author_pseudonym"], unique=False
    )
    op.create_table(
        "communities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("community_index", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("total_comments", sa.Integer(), nullable=False),
        sa.Column("total_likes", sa.Integer(), nullable=False),
        sa.Column("avg_sentiment", sa.Float(), nullable=True),
        sa.Column("cohesion", sa.Float(), nullable=False),
        sa.Column("density", sa.Float(), nullable=False),
        sa.Column("top_influencers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("bridge_users", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_communities_analysis_id_analyses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_communities")),
        sa.UniqueConstraint(
            "analysis_id", "community_index", name=op.f("uq_communities_analysis_id")
        ),
    )
    op.create_index(
        op.f("ix_communities_analysis_id"), "communities", ["analysis_id"], unique=False
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("pseudonym", sa.String(length=64), nullable=False),
        sa.Column("community_index", sa.Integer(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("replies_received", sa.Integer(), nullable=False),
        sa.Column("active_days", sa.Integer(), nullable=False),
        sa.Column("engagement_score", sa.Float(), nullable=False),
        sa.Column("engagement_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pagerank", sa.Float(), nullable=False),
        sa.Column("betweenness", sa.Float(), nullable=False),
        sa.Column("influence_rank", sa.Integer(), nullable=True),
        sa.Column("avg_sentiment", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_nodes_analysis_id_analyses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
        sa.UniqueConstraint("analysis_id", "pseudonym", name=op.f("uq_nodes_analysis_id")),
    )
    op.create_index(op.f("ix_nodes_analysis_id"), "nodes", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_nodes_pseudonym"), "nodes", ["pseudonym"], unique=False)
    op.create_table(
        "raw_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_raw_comments_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_comments")),
    )
    op.create_index(op.f("ix_raw_comments_comment_id"), "raw_comments", ["comment_id"], unique=True)
    op.create_index(
        op.f("ix_raw_comments_expires_at"), "raw_comments", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###

    # Dev-placeholder user + project until real auth arrives (M3, decision A1).
    # M3's migration removes this and wires JWT-backed users.
    _seed_dev_account()


def _seed_dev_account() -> None:
    users = sa.table("users", sa.column("id", sa.Uuid), sa.column("email", sa.String))
    projects = sa.table(
        "projects",
        sa.column("id", sa.Uuid),
        sa.column("user_id", sa.Uuid),
        sa.column("name", sa.String),
    )
    op.bulk_insert(
        users,
        [{"id": "00000000-0000-0000-0000-000000000001", "email": "dev@orbitlink.local"}],
    )
    op.bulk_insert(
        projects,
        [
            {
                "id": "00000000-0000-0000-0000-000000000002",
                "user_id": "00000000-0000-0000-0000-000000000001",
                "name": "Dev project",
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_comments_expires_at"), table_name="raw_comments")
    op.drop_index(op.f("ix_raw_comments_comment_id"), table_name="raw_comments")
    op.drop_table("raw_comments")
    op.drop_index(op.f("ix_nodes_pseudonym"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_analysis_id"), table_name="nodes")
    op.drop_table("nodes")
    op.drop_index(op.f("ix_communities_analysis_id"), table_name="communities")
    op.drop_table("communities")
    op.drop_index(op.f("ix_comments_author_pseudonym"), table_name="comments")
    op.drop_index(op.f("ix_comments_analysis_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_analyses_project_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_analysis_jobs_status"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_project_id"), table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
