"""m4 graph edges

Adds ``analyses.graph_edges``. NOT NULL with a server default of ``'[]'`` so
existing rows (from before this column existed — PR-10's known limitation:
their graph view just shows no edges) backfill cleanly instead of failing the
migration.

Revision ID: 0004_m4_graph_edges
Revises: 0003_m3_auth
Create Date: 2026-09-11 23:01:02.406541
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004_m4_graph_edges"
down_revision: str | None = "0003_m3_auth"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyses",
        sa.Column(
            "graph_edges",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "graph_edges")
    # ### end Alembic commands ###
