"""m5 admin role: users.role + users.suspended_at (specs AD-01/AD-02).

``role`` is NOT NULL with a server default of ``'user'`` so existing rows
backfill cleanly — nobody becomes an admin by accident, they all land on the
same default everyone starts on.

Revision ID: 0006_admin_role
Revises: 0005_feedback
Create Date: 2026-09-16
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006_admin_role"
down_revision: str | None = "0005_feedback"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("role", sa.String(length=20), nullable=False, server_default="user"),
    )
    op.add_column("users", sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "suspended_at")
    op.drop_column("users", "role")
    # ### end Alembic commands ###
